# Generated by Django 5.2.16 on 2026-07-30 10:44

import django.db.models.deletion
from django.db import migrations, models

import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ("python", "0022_pythonblocklistentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageYank",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("name_normalized", models.TextField()),
                ("version", models.TextField()),
                ("yanked_reason", models.TextField(default="")),
                (
                    "_pulp_domain",
                    models.ForeignKey(
                        default=pulpcore.app.util.get_domain_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.domain",
                    ),
                ),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {
                    ("name_normalized", "version", "yanked_reason", "_pulp_domain")
                },
            },
            bases=("core.content",),
        ),
    ]
